### ISSUE TITLE
Buffer is undefined when using Browserify

### ISSUE THREAD

**Issue by felix** [indutny/bn.js#147]
When using Browserify v13.0.1 I get an assertion error of Buffer being undefined. It seems commit 4ef34bdaae8c73a3b616f4e0498d5b119d664aa1 as a result of #115 (or #116?) seems to have broken this. It works for me if the require() call is left as this:

`Buffer = require('buffer').Buffer;`

instead of:

`Buffer = require('buf' + 'fer').Buffer;`

**Comment by indutny** [comment]
This is intentional to reduce the size of javascript library. I think you may try to use `num.toArrayLike(Buffer, endian, length);` in your code to mitigate this.

**Comment by felix** [comment]
Ah, you are right. Thank you.

**Comment by indutny** [comment]
No problem, glad to help!

**Comment by monfera** [comment]
Hello @indutny I've kept running into this for the past year or so and and just skipped the error all the time (basically, all browser reloads which is a lot, and as I'm often in a test runner, Pause On Caught Exceptions must be enabled), but now decided to see what's going on, saw the string concatenation trick and landed here on a search. Too bad I procrastinated as it's one of those dev tool annoyances whose solution was important for me but never urgent :-)

Having read your reply above, I don't entirely follow, how can it reduce the library size if the function would actually be needed? Why include a library otherwise? (I'm definitely missing something.) As it's a very rare practice to trick a module bundler, what's the special circumstance with this library that necessitates it here but not elsewhere? Have you got a link that explains?

**Comment by bj97301** [comment]
What about for external dependencies?  Is there a way to fake the buffer for them without changing each file?

**Comment by mesqueeb** [comment]
I'm having the same problem. Any other way I can achieve this?
`new BN('1000000000000000000').toBuffer()`
in the browser?

My webpack should polyfill Buffer, but it seems there's a scope problem with bn.js where Buffer is still undefined.
