### ISSUE TITLE
bitwise operators on negative numbers

### ISSUE THREAD

**Issue by Yaffle** [indutny/bn.js#48]
seems, https://github.com/justmoon/node-bignum throws an error if any `a` or `b` is a negative integer for `a ^ b`, `a & b`, `a | b`

The behaviour of this operators for negative integers in other libraries and in JavaScript is `as if twos complement arithmetic were used`. ( http://www-cs-students.stanford.edu/~tjw/jsbn/ )

I think, you might throw an error while this behaviour is not implemented

**Comment by indutny** [comment]
I'm -1 for implementing it, cc @dcousens

**Comment by dcousens** [comment]
@indutny it has always felt that negative numbers have been an afterthought in `bn.js`,  thats not to say they aren't supported, but simply due to the use cases for this library being primarily crypto in a reduced context,  they aren't tested as heavily.
Perhaps we need to decide whether they should be first class citizens or not before we start making the APIs more cross-compatible with standard behaviour?

**Comment by indutny** [comment]
@dcousens I didn't really thought much about them indeed, and the mentioned reasons are correct. I wonder if it might be a good idea to fix it within next major bump.

btw, I think I am convinced that it should be done.

**Comment by dcousens** [comment]
@indutny if we are going to continue to support negative numbers (I think we should),  then yes, it should be done absolutely.
